branches:
  only:
    - master
sudo: false
language: node_js
node_js:
  - 8.11.1
install:
  - echo Installing packages ...
  - npm install
  - echo Installing and compiling contracts ...
  - mkdir contracts
  - cd contracts
  - git clone https://github.com/CirclesUBI/circles-contracts.git .
  - npm install
  - npx truffle compile
  - cd ..
  - mkdir src
before_script:
  - echo Creating environment config file
  - npm i -g create-env
  - create-env --env-file .env --env-prefix TEST_
  # - touch .env
  # - |
  #   tee .env > /dev/null <<-EOF \
  #   -- AWS_REGION=$AWS_REGION \
  #   -- USER_POOL_ID=$USER_POOL_ID \
  #   -- USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID \
  #   -- API_TEST_ENDPOINT=$API_TEST_ENDPOINT \
  #   -- EOF
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - npm i -g expo-cli
  - expo login -u circlesubi -p $EXP_PASSWORD
script:
  - expo publish
