branches:
  only:
    - master
sudo: false
language: node_js
node_js:
  - 10.15.0
install:
  - echo Installing packages ...
  - npm install
  - echo Installing and compiling contracts ...
  - cd contracts
  - git checkout master 
  - git pull
  - npm install
  - npx truffle compile
  - cd ..
  - mkdir src
before_script:
  - echo Creating environment config file
  - npm i -g create-env
  - export TEST_TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - create-env --env-file .env --env-prefix TEST_  
  # - touch .env
  # - |
  #   tee .env > /dev/null <<-EOF \
  #   -- AWS_REGION=$AWS_REGION \
  #   -- COGNITO_POOL_ID=$COGNITO_POOL_ID \
  #   -- COGNITO_CLIENT_ID_MOBILE=$COGNITO_CLIENT_ID_MOBILE \
  #   -- API_TEST_ENDPOINT=$API_TEST_ENDPOINT \
  #   -- EOF
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - npm i -g expo-cli
  - expo login -u circlesubi -p $EXP_PASSWORD
script:
  - expo publish
