branches:
  only:
    - master
sudo: false
language: node_js
node_js:
  - 8.11.1
install:
  - npm install
  - mkdir src
before_script:
  - npm i -g expo-cli
  - expo login -u circlesubi -p $EXP_PASSWORD
script:
  - expo publish
