branches:
  only:
    - master

sudo: false

language: node_js

node_js:
  - 8.11.1

install:
  - npm install

script:
  - npm test

beforeDeploy:
  - npm i -g exp
  - exp login -u edzillion -p $EXP_PASSWORD

deploy:
  provider: script
  script: exp publish
  on:
    branch: master