branches:
  only:
    - master
sudo: false
language: node_js
node_js:
  - 8.11.1
install:
  - npm install
before_script:
  - npm i -g exp
  - exp login -u edzillion -p $EXP_PASSWORD
script:
  # - npm test (build stalls here)
  - exp publish