// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-central-1:459201c8-1960-480b-9bad-7b5deeaf8dd6',
    'aws_cognito_region': 'eu-central-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'circlesmobile-hosting-mobilehub-667418163',
    'aws_content_delivery_bucket_region': 'eu-central-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd25vz0adwcr05o.cloudfront.net',
    'aws_mobile_analytics_app_id': '9e0ca1c673014be4bd683f251f4c609a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '770910f7-fd56-4dde-8c4a-a2eb555047c7',
    'aws_project_name': 'circles-mobile',
    'aws_project_region': 'eu-central-1',
    'aws_resource_name_prefix': 'circlesmobile-mobilehub-667418163',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'circlesmobile-userfiles-mobilehub-667418163',
    'aws_user_files_s3_bucket_region': 'eu-central-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-central-1_9trhIbHPD',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '1f0h42ltnol2idc928q1fcd41h',
}

export default awsmobile;
