export const FETCH_CURRENT_COUNTRY = 'FETCH_CURRENT_COUNTRY'
export const ADD_DATA = 'ADD_DATA'
export const SAVE_PROFILE_IMAGE = 'SAVE_PROFILE_IMAGE'
export const SET_VERIFICATION_STATE = 'SET_VERIFICATION_STATE'
